# Szakirodalom {#Chapter-3}

```{css, echo=FALSE}
p {
text-align: justify;
  }
```

Termékenységi rátát befolyásoló tényezők empirikus elemzése alapvetően három módon történik meg a szakirodalom: (1) a teljes termékenységi rátának kohorszokra bontott értékeinek elemzéséből, (2) egy adott ország adatainak elemzése idősoros, vagy egyszerű leíró statisztikai eszközökkel, (3) lakosságkörében készített kérdőíves kutatás anyagaiból, (4) több ország adatainak elemzése keresztmetszeti- vagy panelökonometriai eszközökkel.
Az első csoportba tartozók közül kiemelném *Bongaarts* és *Feeney* (2006) munkáját, akik a TTA azon problémáját hangsúlyozták, hogy az nem veszi figyelembe az szülővé válás életkori években való kitolósását, így téves következtetésre utalhat. *Berde* és *Németh* (2014) ennek mentén magyarázza, hogy a 21. század eleji drasztikusan alacsony termékenységi szám Magyarországon (2011-ben 1,23, bőven a kritikusnak tartott 1,3 alatt) valójában némileg enyhébb probléma, mert éppen akkora esett az első gyermek szülés modulus évének kitolódása. A cikkek igen fontosak, abból a szempontból, hogy miként viszonyulunk a modellek eredményeihez, azonban mivel nincs mód megyei szintű bontásra ütem szerint kiigazított termékenységi rátában, így e az irány sajnos megmarad egyelőre lehetséges további kutatási iránynak.
A második csoportból főleg magyar szerzők cikkeit tartom relevánsnak a kutatás szempontjából. *Tárkányi* (2008) egyszerű leíró statisztikai következtetéseket alkalmazva jutott arra a konklúzióra, hogy a rendszerváltás követően több közép-európai országban is zuhant a termékenységi ráta, amely a munkanélküliség emelkedése és az egy főre jutó bruttó kibocsátás csökkenése okán történhetett. Ez az elemzés fontos támpontja ennek a tanulmánynak is. Ebben a csoportban említeném még *Cigno és társainak* (2001) termékenységi rátát tartalmazó VAR-modellezését, mellyel az általam választott modellezési eszköz helyességét kívánom alátámasztani. 
A harmadik csoportból kiemelném *König* (2011) munkáját, aki összehasonlítást végzett logit modellel a német és a magyar lakosság körében készített kérdőívből (*Generations- and Gender Surveys*) és azt találta, hogy a munkanélküliség csökkenti a gyermekvállalási hajlandóságot, míg a jövedelem növeli azt, azonban munkanélküliként a jövedelem csökkenése növeli (interakció). Ami még érdekesebb tanulmányában, hogy míg Németország esetében a nők oktatásban való részvétele növeli a gyermekvállalási hajlandóságot, akkor is, ha a modell tartalmazza jövedelmet, addig Magyarország esetében az oktatás hozzáadott értéke elvész, ha a modellben kontrolálás történik a jövedelemre.
A negyedik csoportból kiemelném *Götmark* és *Andersson* (2020) munkáját, akik több ország adatait felhasználva azt találták, hogy a GDP negatívan korrelál a TTA-val. Ezzel ellentmond a *Tárkányi* (2008) és *König* (2011) által leközölt hatásiránynak. Ily módon **empirikus elemzésem megkezdése előtt a bruttó kibocsátás TTA-ra gyakorolt hatásának előjelére előzetesen nem fogalmazok meg hipotézist**.
A szezőpáros emelett a több ország TTA adatainak panelökonometriai elemzésével szemben érvel a területi hasonlóságra hivatkozva. Ezt az érvelést szintén alá kívánom támasztani tanulmányomban. Ennél komplexebb formulát határozott meg a GDP és a TTA kapcsolatára *Kreiszné Hudák* (2019:207). Ő a GDP/fő PPP (USD) kvadratikus hatását írta le egy U alakú görbeként, ahol a legalacsonyabb TTA értékkel rendelkező országok 33 ezer dollár körül határozta meg.
