# A magyar születésszám az elmúlt 60 évben {#Chapter-2}

```{css, echo=FALSE}
p {
  text-align: justify;
}
```

Ahhoz, hogy a születendő gyermekek számának alakulásában lezajló trendek mögötti okozati kapcsolatokat értelmezni tudjuk elengedhetetlen a születésszámmal kapcsolatos indikátorok fogalmainak tisztázása, és mind az erről szóló viták, mind a modellezéssel kapcsolatosan az egyik legkritikusabb pont a megfelelő mutató kiválasztása. Ennek elvégzéséhez ezen szakaszban szeretném az általánosan ismert mutatókat röviden bemutatni. A Központi Statisztikai Hivatal honlapján is elérhető a téma három legelemibb mutatója: a született gyermekek száma összesen, az ezer főre jutó gyermekek száma, illetőlegesen a teljes termékenységi arányszám.
Az előbbi felsorolás sorrendjében haladva, ezen indikátorok egyre érzéketlenebbek az ország népességének meglévő helyzetével kapcsolatosan. Az összes gyermekszületésének számossága teljes mértékben összefügg az adott évben, adott országban élő nők számával, ily módon már csak attól is képes változni az értéke, hogy az ország populációjának mértéke megváltozik. Azaz, ha az anyákat jellemző gyermekvállalási hajlamban nem is történik változás, pusztán az országban élő nők száma növekszik vagy csökken, akkor is megváltozik az értéke. Az ezer főre jutó születésszám az imént említett eseményre érzéketlen. Azonban nem szűrődik ki belőle a populáció összetételében zajló elváltozás. Ez leggyakrabban a populáció elöregedésében érhető tetten a fejlett országokban, mivel a népesség száma nem egyenlő mértékben változik a szülőképes korú nőkkel. Szélsőséges esetben azonban történhet ez akár a nemek arányainak felborulásán keresztül is, ahogy történik ez a mai Kínában a szelektív abortusz eredményeként.^[A bevezetett egy gyermek politika jelent olyan ösztönzőket az emberek számára, hogy gazdasági megfontolásból inkább szeretnének fiú utódot, ami ahhoz vezetett, hogy 30 millióval fővel kisebb a kínai női populáció, mint a férfi (The Economist 2019).]
A felsorolás sorrendjének megfelelően pedig a teljes termékenységi arányszám (továbbiak TTA) bemutatása az, amelyre most rá szeretnék térni. A teljes termékenységi arányszám kiszámítási módjához szükségessé válik a születési kohorsz fogalmának bevezetése, mellyel az azonos évben születtek csoportját illetjük. Definíciója szerint a TTA kiszámítása során minden gyermekvállalási életkorba eső kohorsz által adott évben világra hozott gyermekek számát elosztjuk a kohorsz létszámával, így megkapva annak a feltételes valószínűségét, hogy amennyiben adott nő adott kohorszhoz tartozik, mennyi a valószínűsége, hogy abban az évben gyermeket vállalt. Ezeket a valószínűségeket összegezve kapjuk meg a teljes termékenységi arányszámot. Ebből kiindulva tehát a TTA hipotetikus jellegű mutató és arra a kérdésre válaszol, hogy várhatóan hány gyermeknek adna életet egy nő élete folyamán, ha most lépne be a gyermekvállalási életkorba (most töltené be a 15. életévét) (Központi Statisztikai Hivatal 2018). Ezen számítási módot figyelembe véve tehát elmondható, hogy a TTA mentes mind az ország népességének számosságától, mind a lakosság összetételétől.
Annak megválaszolásához, hogy mekkora eltéréshez vezet az eltérő mutatók alkalmazása érdemes a mutatókban való relatív változások vizsgálatát elvégezni. Azért, hogy a három mutatót egymás mellett lehessen szemléltetni 1960-as évi bázisindexüket tüntettem fel az 1. ábrán.

```{r fig.height=3.5, fig.cap="Születési mutatók bázisindexe (1960=100%)"}
LiveBirthAndFertility %>%
  mutate_at(-1, function(x) x / x[1]) %>%
  pivot_longer(-1) %>%
  mutate(
    name = factor(case_when(
      name == "LiveBirthTotal" ~ "Születésszám",
      name == "LiveBirthTo1000" ~ "Ezer főre eső születésszám",
      T ~ "Teljes termékenységi arányszám"
    ), levels = c("Teljes termékenységi arányszám", "Ezer főre eső születésszám",
                  "Születésszám"))
  ) %>%
  ggplot() +
  geom_hline(aes(
    yintercept = 2.1 / LiveBirthAndFertility$TotalFertility[1],
    linetype = "Reprodukciót biztosító TTA érték"
  ), color = "black", size = 1) +
  geom_line(aes(x = Year, y = value, color = name), size = 2) +
  scale_color_grey() +
  scale_linetype_manual(values = 
                      c("Reprodukciót biztosító TTA érték" = "dotted")) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Év", y = "Százalék (1960 = 100%)", color = NULL,
       linetype = NULL, title = "Születési mutatók bázisindexe (1960=100%)") 
```

Egy olyan hipotetikus esetben, amelyben az ország népességége és korfájának összetétele állandó, pusztán a gyermekvállalási hajlandóságban történik változás, azt várhatjuk, hogy a három mutató egymáshoz viszonyított aránya állandó marad. Az 1. ábráról jól kivehető, hogy a három tárgyalt mutató bázisindexe (1960-as évekhez hasonlított mértéke) alapvetően az 1970-es évek közepén érte el az egymástól vett eltérés maximumát. Az eltérés kialakulásának oka az 1980-as évek elejéig tapasztalható népességszám növekedés. Az 1970-es évek közepén a hirtelen termékenység növekedésnek hátterében az abortuszengedélyezési eljárás szigorítása, illetőleg a gyes bevezetése állt (Spéder 2019), azonban a 20 évvel korábban a Ratkó-korszakban született nők gyermekvállalási korba lépése a másik két mutató emelkedését felerősítette, míg a TTA mentes a legutóbbi hatásától (KSH, 2018).
Az 1980-as évektől kezdődően Magyarország lakosságát csökkenés jellemzi, ily módon a TTA bázisindexe a teljes születésszám bázisindexe fölé került, azaz a szülőképes korú nők számosságában beálló csökkenés miatt a született gyermekek száma nagyobb mértékben csökkent, mint a gyermek vállalási hajlandóság. 2010-et követően pedig ismételten azzal a helyzettel állunk szemben, hogy bár a TTA jelentős mértkében növekszik, ez nem nyilvánul meg az évenkénti gyermekszületés növekedésében. Annak függvényében melyik mutatót választjuk eltérő eredményeket kaphatunk amikor más változókkal való együttmozgásukat figyeljük, kiemelten fontos erre figyelni mikor az elmúlt évtized tendenciára fordítjuk figyelmünket. Például, ha a családtámogatások sikerét akarjuk értékelni az elmúlt néhány évben, akkor az évente született gyermekek száma alapján azt látnánk nincs növekedés, míg a TTA növekedést mutat. Döntő kérdés, hogy szükséges-e figyelembe venni a vizsgálat során a korfában már meglévő változásokat. Egy családtámogatás értékelésekor például akkor tekinthetjük, hogy a gyermekvállalási hajlandóságot sikerült emelni, ha a teljes termékenységi ráta növekedett, az mellékes kérdés, hogy a korábbi években lezajló folyamatok olyan módon alakították a gyermekvállalási korban lévő nők számát, hogy a teljes születésszám ennek ellenére stagnál. Ellenben, ha a szülőképes korú nők számában történő változás az emigráció hatása, amely pedig a vizsgált magyarázó változóval lehet kapcsolatban, úgy a teljes születésszámot érdemes elemezni. Mindazonáltal a tény, hogy a magyar termékenységi ráta lényegesen a 2,1-es populáció egyszerű reprodukcióját biztosító határ alatt mozgott az utóbbi félévszázadban (néhány évet a 1970-es években leszámítva) a népességnek zéró nettó migrációs hatás mellett is csökkennie kellett ekkor az időszakban. A várható élettartam növekedéséből adódóan a népességszám tud stagnálni, illetőleg növekedni is azon években is, amikor a TTA nem éri el a 2,1-es szintet, azonban ilyenkor a népesség elöregedése következik be. Hasonló módon pozitív nettó migrációs mérleg mellett is lehetséges, hogy egy ország népessége úgy növekedjen, hogy a TTA közben az említett érték alatt van. Az anyánkként számolt átlagos 2,1 gyermek tehát a migráció és a halandósági ráta változatlansága mellett biztosítja a reprodukciót (OECD 2019). A kettőhöz hozzáadott 0,1 oka pedig az alacsony csecsemőhaladósági ráta figyelembevétele.
Az előbbiekben ismertettek alapján belátható, hogy mivel a vizsgált időszakban az alacsony termékenységi rátából fakadóan változások álltak be a magyar szülőképes korú nők számában. Így indokolt a születésszám alakulását befolyásoló tényezők hatását a TTA-ra vetítve vizsgálni, ezzel leválasztva a gyermekszületésszámban történő változás azon részét, amelyet egyszerűen a népességszáma és összetétele okoz.