# Bevezetés {#Chapter-1}

```{css, echo=FALSE}
p {
text-align: justify;
  }
```

Tanulmányomban elemezni kívánom a termékenységi ráta kapcsolatát az egy főre eső bruttó kibocsátással és a munkanélküliségi rátával. A dolgozat főként az idősor- és panelökonometria eszközeire támaszkodom, a választott eszközök: Engel-Granger teszt, vektor autoregresszív modellek, fixhatású longitudinális modell.
Elsőként az OECD által közölt termékenységi rátákon végzek kointegrációs vizsgálatot, ahol hipotézisem, hogy egymással szomszédos országok termékenységi arányszámai hasonló pályát járnak be, ami a közös gazdasági- és kulturális környezetből fakad. Ezt követően VAR modellel elemzem a termékenységi ráta, a GDP/fő és munkanélkülisági ráta kapcsolatát. Végül panel modellt készítek az előbb a termékenységi rátára, ahol megyei szintű adatokat használok fel. Ezzel az általam elért szakirodalomban nem találkoztam, és ahogyan az az irodalom feldolgozásomból majd kitűnik, eltérő eszközök eltérő irányú hatást mutatnak ki a jövedelem és a gyermekvállalási hajlandóság között. Ennek megfelelően a hatások irányára előzetes hipotézist nem teszek fel.